bool canada = false;
bool waterloo = false;

List<String> canadaNames = [
  "whitehorse",
  "yellowknife",
  "iqaluit",
  "victoria",
  "edmonton",
  "regina",
  "winnipeg",
  "toronto",
  "quebec",
  "fredericton",
  "halifax",
  "charlottetown",
  "saint john's"
];
List<String> waterlooNames = [
  "accelerator centre waterloo",
  "arts lecture hall",
  "autonomous vehicle research and intelligence laboratory",
  "biology one",
  "biology two",
  "bc matthews hall",
  "brubacher house",
  "bright starts co-operative early learning centre",
  "chemistry two",
  "conrad grebel university college",
  "columbia icefield",
  "columbia lake village north",
  "columbia lake village",
  "columbia greenhouses",
  "commissary",
  "carl a pollock hall",
  "central services building",
  "william g davis computer research centre",
  "douglas wright engineering building",
  "engineering two",
  "engineering three",
  "engineering five",
  "engineering six",
  "engineering seven",
  "east campus one",
  "east campus two",
  "east campus three",
  "east campus four",
  "east campus five",
  "east campus hall",
  "centre for environmental and information technology",
  "energy research centre",
  "earth sciences and chemistry",
  "environment one",
  "environment two",
  "environment three",
  "health expansion building",
  "federation hall",
  "graduate house",
  "general services complex",
  "jg hagey hall of the humanities",
  "health services",
  "lyle s hallman institute for health promotion",
  "dana porter library",
  "mathematics three",
  "mathematics and computer building",
  "minota hagey residence",
  "william lyon mackenzie king village",
  "modern languages",
  "ira g needles hall and extension",
  "school of optometry and vision science",
  "physical activities complex",
  "psychology, anthropology, sociology",
  "physics",
  "mike and ophelia lazaridis quantum-nano centre",
  "research advancement centre",
  "research advancement centre two",
  "jr coutts engineering lecture hall",
  "renison university college",
  "ron eydt village",
  "south campus hall",
  "student life centre",
  "science teaching complex",
  "st. jerome's university",
  "st. paul's university college",
  "william m tatham centre for co-operative education and career action",
  "toby jenkins applied health research building",
  "tutor's houses",
  "university club",
  "university of waterloo place",
  "student village one"
];
